### ISSUE TITLE
java-sdk跑redis demo报错

### ISSUE THREAD

**Issue by LXPWing** [layotto/java-sdk#20]
### 环境：
- layotto：最新
- sdk: 最新
- redis：按照sdk readme文档用docker跑最新的镜像

跑sdk的example模块中的state例子，会报`UNKNOWN: INVALID_ARGUMENT: state store redis is not found`
![image](https://user-images.githubusercontent.com/65880844/174625499-f233d99f-a25d-45e0-92b1-812e22822a30.png)
![image](https://user-images.githubusercontent.com/65880844/174625538-172fe4d5-cda5-4eed-adab-82a87e448d7e.png)

127.0.0.1:58258通过lsof -i:xxxxx 查看没有任何进程占用，是不是还要启动什么。

**Comment by LXPWing** [comment]
cc @seeflood

**Comment by seeflood** [comment]
应该是因为 之前 state store的名字被改了，改成了 state_demo
![image](https://user-images.githubusercontent.com/26001097/174710421-7a45f0af-8926-4743-ac79-33614e73f945.png)
但是demo里传的 storename 还是 redis，见 https://github.com/layotto/java-sdk/blob/7256754f2a3d766e61c7ba22ab4bbc956275ad56/examples/src/test/java/io/mosn/layotto/examples/state/RedisCRUD.java#L28
你试下把 demo里的storename 改成 `state_demo` 看看还报错不？

**Comment by LXPWing** [comment]
ok，改成state_demo不会报错了

**Comment by seeflood** [comment]
fixed by #21
