### ISSUE TITLE
CI failed when building preview server image

### ISSUE THREAD

**Issue by seeflood** [layotto/java-sdk#32]
![image](https://user-images.githubusercontent.com/26001097/189095108-ce4d0ca0-31f2-4ec7-a9f3-51192444c0c6.png)

https://github.com/layotto/java-sdk/runs/8246054552?check_suite_focus=true

![image](https://user-images.githubusercontent.com/26001097/189094694-b13575a4-5c67-446b-b028-588473bad818.png)

**Comment by seeflood** [comment]
😭 @LXPWing Could u help check this error ? It's weird

**Comment by LXPWing** [comment]
Step 1/3 : FROM java:8 manifest for java:8 not found: manifest unknown: manifest unknown. maybe "java:8"has been changed in docker hub

**Comment by LXPWing** [comment]
i fix it

**Comment by seeflood** [comment]
> eeeee @seeflood What code has been changed in the preview server

These are the changes since last success. But they seem irrelevant with this error?
![image](https://user-images.githubusercontent.com/26001097/189100734-83a921b6-161b-4a26-8fe2-fe37115585f4.png)

**Comment by seeflood** [comment]
![image](https://user-images.githubusercontent.com/26001097/189112838-423c5e9b-5836-4196-9c48-b62f5eea89d2.png)
@LXPWing It's ok now. Awesome !
