### ISSUE TITLE
Remove java code in mosn/layotto repo

### ISSUE THREAD

**Issue by seeflood** [layotto/java-sdk#6]
- Remove [java code in mosn/layotto repo](https://github.com/mosn/layotto/tree/main/sdk/java-sdk)
- Add a link [like js-sdk's](https://github.com/mosn/layotto/tree/main/sdk/js-sdk)

**Comment by seeflood** [comment]
@kevinten10 Hi ,could you help do it? So that your avatar will show in the [statistic page](https://github.com/mosn/layotto/graphs/contributors)

**Comment by kevinten10** [comment]
Thanks! Please assign to me.

**Comment by seeflood** [comment]
> Thanks! Please assign to me.

Sure!
